version: '3.4'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - database
    ports:
      - "5000:5000"
    volumes:
      - .:/tips
    env_file: .env
    environment:
      RAILS_ENV: development
      DATABASE_URL: postgres://postgres@database

  database:
    image: postgres:12.1
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: